server:
  port: 9090

spring:
  application:
    name: spf-oauth
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: dba
    password: spfcore@2018
    url: jdbc:mysql://192.168.0.81:3306/spf_auth?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai
  redis:
    host: 192.168.0.81
    port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}

ignore:
  urls:
    - /auth/**
    - /**/*.css
    - /social
    - /login
    - /logout
    - /info
    - /health
    - /metrics/**
    - /loggers/**
    - /mobile/token
