server:
  port: 8080

spring:
  application:
    name: spf-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}

zuul:
  routes:
    upms:
      path: /upms/**
      sensitiveHeaders:
      serviceId: spf-upms
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: spf-oauth
    oauth:
      path: /oauth/**
      url: http://localhost:9090/oauth
  add-proxy-headers: true

security:
  oauth2:
    client:
      access-token-uri: http://localhost:9090/oauth/token
      user-authorization-uri: http://localhost:9090/oauth/authorize
      client-id: webapp
      client-secret: 123
      grant-type: client_credentials
    resource:
      user-info-uri: http://localhost:9090/user
      prefer-token-info: false

ignore:
  urls:
    - /oauth/token
    - /oauth/authorize
    - /uaa/resource/**
